// <auto-generated />
using ClashRoyaleApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClashRoyaleApi.Migrations
{
    [DbContext(typeof(TroopContext))]
    [Migration("20260511211806_vDeux")]
    partial class vDeux
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("ClashRoyaleApi.Models.Troop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ElixirCost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Troops");
                });

            modelBuilder.Entity("ClashRoyaleApi.Models.Troop", b =>
                {
                    b.OwnsOne("ClashRoyaleApi.StatsList.StatsList", "Stats", b1 =>
                        {
                            b1.Property<int>("TroopId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("TroopId");

                            b1.ToTable("Troops");

                            b1.WithOwner()
                                .HasForeignKey("TroopId");

                            b1.OwnsOne("ClashRoyaleApi.StatsList.CountType", "Count", b2 =>
                                {
                                    b2.Property<int>("StatsListTroopId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<double?>("BarrelCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("BrigadeCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("BushGoblinCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("ChargeCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Count")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("DeathSpawnCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("DecoyGoblinCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("GeneralCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("GoblinBrawlerCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("GoblinCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("GrenadeCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("MaxCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("MaxSkeletonCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("MinSkeletonCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("ProjectileCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("RascalBoyCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("RascalGirlCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("RiderCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("SkeletonCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("SniperAmmo")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("SpawnCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("SpearGoblinCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("TargetCount")
                                        .HasColumnType("REAL");

                                    b2.HasKey("StatsListTroopId");

                                    b2.ToTable("Troops");

                                    b2.WithOwner()
                                        .HasForeignKey("StatsListTroopId");
                                });

                            b1.OwnsOne("ClashRoyaleApi.StatsList.DamageType", "Damage", b2 =>
                                {
                                    b2.Property<int>("StatsListTroopId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<double?>("AreaDamage")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("BarrageDamage")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("BonusDamage")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("BounceDamage")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("BuildingDamagePerSecond")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("ChargeDamage")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("CloseQuartersDamage")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("ComboDamage")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("CrownTowerDamage")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("CrownTowerDamagePerPercent")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("CrownTowerDamagePerSecond")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Damage")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("DamagePerBlast")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("DamagePerSecond")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("DashDamage")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("DeathDamage")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("ExtraChainDamage")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("IceBlastDamage")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("JumpDamage")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("LandingDamage")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("MeleeDamage")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("PoisonDamagePerSecond")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("PowerShotDamage")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("PulseDamage")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("PushbackDamage")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("RangedDamage")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("RecoilDamage")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("ReflectDamage")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("ReflectedTowerDamage")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("SniperDamage")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("SpawnDamage")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("TornadoDamage")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("TripleShotDamage")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("TurretDamage")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("WarpDamage")
                                        .HasColumnType("REAL");

                                    b2.HasKey("StatsListTroopId");

                                    b2.ToTable("Troops");

                                    b2.WithOwner()
                                        .HasForeignKey("StatsListTroopId");
                                });

                            b1.OwnsOne("ClashRoyaleApi.StatsList.DurationType", "Duration", b2 =>
                                {
                                    b2.Property<int>("StatsListTroopId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<double?>("BannerLifetime")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("BoostDuration")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("CastTime")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("ChargedDuration")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("CookingTime")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Cooldown")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("DecoyDuration")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("DeployTime")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Duration")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("FreezeDuration")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("HotSpawnSpeed")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("InvincibilityDuration")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("InvisibilityDuration")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Lifetime")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("NetCooldown")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("NetDuration")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("PoisonDuration")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("ProductionSpeed")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("PulseDuration")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("SlowdownDuration")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("SnareDuration")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("SpawnSpeed")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("StunDuration")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("TauntDuration")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("TornadoDuration")
                                        .HasColumnType("REAL");

                                    b2.HasKey("StatsListTroopId");

                                    b2.ToTable("Troops");

                                    b2.WithOwner()
                                        .HasForeignKey("StatsListTroopId");
                                });

                            b1.OwnsOne("ClashRoyaleApi.StatsList.HitpointsType", "Hitpoints", b2 =>
                                {
                                    b2.Property<int>("StatsListTroopId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<double?>("CloneHitpoints")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("CloneShieldHitpoints")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("DecoyHitpoints")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Hitpoints")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("MaxHitpoints")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("ShieldHitpoints")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("TurretHitpoints")
                                        .HasColumnType("REAL");

                                    b2.HasKey("StatsListTroopId");

                                    b2.ToTable("Troops");

                                    b2.WithOwner()
                                        .HasForeignKey("StatsListTroopId");
                                });

                            b1.OwnsOne("ClashRoyaleApi.StatsList.MechanicType", "Mechanic", b2 =>
                                {
                                    b2.Property<int>("StatsListTroopId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<double?>("AlliesBuff")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("AlliesSpeedBoost")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("BackwardTeleport")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Barrage")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("BuildingSummon")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Charge")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Clone")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Curse")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("DamageBoost")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("DamageReduction")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Dash")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("DualForm")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("ElixirCollect")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("EnemiesSpeedReduction")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Freeze")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Grab")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Heal")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Invincibility")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Invisible")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Jump")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("KeepMaxDamage")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Knockback")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Mirror")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("MultipleTroops")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("MultiplesDash")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("PullToCenter")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Redeploy")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("ReflectProjectiles")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Resurrect")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("SecondaryAttack")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Shield")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("SideSwitchTeleport")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Slow")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Snare")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("SoulsCollect")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("SpellSummon")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Stun")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("SwitchToAir")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("SwitchToBuilding")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("SwitchToGround")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Taunt")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("TroopSummon")
                                        .HasColumnType("REAL");

                                    b2.HasKey("StatsListTroopId");

                                    b2.ToTable("Troops");

                                    b2.WithOwner()
                                        .HasForeignKey("StatsListTroopId");
                                });

                            b1.OwnsOne("ClashRoyaleApi.StatsList.MovementType", "Movement", b2 =>
                                {
                                    b2.Property<int>("StatsListTroopId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<double?>("Air")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Ground")
                                        .HasColumnType("REAL");

                                    b2.HasKey("StatsListTroopId");

                                    b2.ToTable("Troops");

                                    b2.WithOwner()
                                        .HasForeignKey("StatsListTroopId");
                                });

                            b1.OwnsOne("ClashRoyaleApi.StatsList.RangeType", "Range", b2 =>
                                {
                                    b2.Property<int>("StatsListTroopId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<double?>("Long")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Medium")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Ranged")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Short")
                                        .HasColumnType("REAL");

                                    b2.HasKey("StatsListTroopId");

                                    b2.ToTable("Troops");

                                    b2.WithOwner()
                                        .HasForeignKey("StatsListTroopId");
                                });

                            b1.OwnsOne("ClashRoyaleApi.StatsList.SpeedType", "Speed", b2 =>
                                {
                                    b2.Property<int>("StatsListTroopId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<double?>("Fast")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Medium")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Slow")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("VeryFast")
                                        .HasColumnType("REAL");

                                    b2.HasKey("StatsListTroopId");

                                    b2.ToTable("Troops");

                                    b2.WithOwner()
                                        .HasForeignKey("StatsListTroopId");
                                });

                            b1.OwnsOne("ClashRoyaleApi.StatsList.TargetType", "Target", b2 =>
                                {
                                    b2.Property<int>("StatsListTroopId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<double?>("Air")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Both")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Buildings")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Ground")
                                        .HasColumnType("REAL");

                                    b2.HasKey("StatsListTroopId");

                                    b2.ToTable("Troops");

                                    b2.WithOwner()
                                        .HasForeignKey("StatsListTroopId");
                                });

                            b1.OwnsOne("ClashRoyaleApi.StatsList.TriggerType", "Trigger", b2 =>
                                {
                                    b2.Property<int>("StatsListTroopId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<double?>("Activation")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("OnAttack")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("OnChargeComplete")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("OnClick")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("OnDamageTaken")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("OnDeath")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("OnDeploy")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("OnDurationEnd")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("OnHit")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("OnTargetReached")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Passive")
                                        .HasColumnType("REAL");

                                    b2.HasKey("StatsListTroopId");

                                    b2.ToTable("Troops");

                                    b2.WithOwner()
                                        .HasForeignKey("StatsListTroopId");
                                });

                            b1.Navigation("Count");

                            b1.Navigation("Damage");

                            b1.Navigation("Duration");

                            b1.Navigation("Hitpoints");

                            b1.Navigation("Mechanic");

                            b1.Navigation("Movement");

                            b1.Navigation("Range");

                            b1.Navigation("Speed");

                            b1.Navigation("Target");

                            b1.Navigation("Trigger");
                        });

                    b.OwnsOne("ClashRoyaleApi.StatsList.TroopType", "TroopType", b1 =>
                        {
                            b1.Property<int>("TroopId")
                                .HasColumnType("INTEGER");

                            b1.Property<double?>("Building")
                                .HasColumnType("REAL");

                            b1.Property<double?>("Spell")
                                .HasColumnType("REAL");

                            b1.Property<double?>("Troop")
                                .HasColumnType("REAL");

                            b1.HasKey("TroopId");

                            b1.ToTable("Troops");

                            b1.WithOwner()
                                .HasForeignKey("TroopId");
                        });

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("TroopType")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
