// <auto-generated />
using ClashRoyaleApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClashRoyaleApi.Migrations
{
    [DbContext(typeof(TroopContext))]
    [Migration("20260511213232_ConvertCategoryTypesToEnums")]
    partial class ConvertCategoryTypesToEnums
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("ClashRoyaleApi.Models.Troop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ElixirCost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TroopType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Troops");
                });

            modelBuilder.Entity("ClashRoyaleApi.Models.Troop", b =>
                {
                    b.OwnsOne("ClashRoyaleApi.StatsList.StatsList", "Stats", b1 =>
                        {
                            b1.Property<int>("TroopId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Mechanic")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Movement")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Speed")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Target")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Trigger")
                                .HasColumnType("TEXT");

                            b1.HasKey("TroopId");

                            b1.ToTable("Troops");

                            b1.WithOwner()
                                .HasForeignKey("TroopId");

                            b1.OwnsOne("ClashRoyaleApi.StatsList.CountType", "Count", b2 =>
                                {
                                    b2.Property<int>("StatsListTroopId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<double?>("BarrelCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("BrigadeCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("BushGoblinCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("ChargeCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Count")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("DeathSpawnCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("DecoyGoblinCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("GeneralCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("GoblinBrawlerCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("GoblinCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("GrenadeCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("MaxCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("MaxSkeletonCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("MinSkeletonCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("ProjectileCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("RascalBoyCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("RascalGirlCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("RiderCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("SkeletonCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("SniperAmmo")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("SpawnCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("SpearGoblinCount")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("TargetCount")
                                        .HasColumnType("REAL");

                                    b2.HasKey("StatsListTroopId");

                                    b2.ToTable("Troops");

                                    b2.WithOwner()
                                        .HasForeignKey("StatsListTroopId");
                                });

                            b1.OwnsOne("ClashRoyaleApi.StatsList.DamageType", "Damage", b2 =>
                                {
                                    b2.Property<int>("StatsListTroopId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("AreaDamage")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("BarrageDamage")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("BonusDamage")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("BounceDamage")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("BuildingDamagePerSecond")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("ChargeDamage")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("CloseQuartersDamage")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("ComboDamage")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("CrownTowerDamage")
                                        .HasColumnType("INTEGER");

                                    b2.Property<double?>("CrownTowerDamagePerPercent")
                                        .HasColumnType("REAL");

                                    b2.Property<int?>("CrownTowerDamagePerSecond")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("Damage")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("DamagePerBlast")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("DamagePerSecond")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("DashDamage")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("DeathDamage")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("ExtraChainDamage")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("IceBlastDamage")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("JumpDamage")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("LandingDamage")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("MeleeDamage")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("PoisonDamagePerSecond")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("PowerShotDamage")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("PulseDamage")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("PushbackDamage")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("RangedDamage")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("RecoilDamage")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("ReflectDamage")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("ReflectedTowerDamage")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("SniperDamage")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("SpawnDamage")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("TornadoDamage")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("TripleShotDamage")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("TurretDamage")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("WarpDamage")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("StatsListTroopId");

                                    b2.ToTable("Troops");

                                    b2.WithOwner()
                                        .HasForeignKey("StatsListTroopId");
                                });

                            b1.OwnsOne("ClashRoyaleApi.StatsList.DurationType", "Duration", b2 =>
                                {
                                    b2.Property<int>("StatsListTroopId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<double?>("BannerLifetime")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("BoostDuration")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("CastTime")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("ChargedDuration")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("CookingTime")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Cooldown")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("DecoyDuration")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("DeployTime")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Duration")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("FreezeDuration")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("HotSpawnSpeed")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("InvincibilityDuration")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("InvisibilityDuration")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Lifetime")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("NetCooldown")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("NetDuration")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("PoisonDuration")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("ProductionSpeed")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("PulseDuration")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("SlowdownDuration")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("SnareDuration")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("SpawnSpeed")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("StunDuration")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("TauntDuration")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("TornadoDuration")
                                        .HasColumnType("REAL");

                                    b2.HasKey("StatsListTroopId");

                                    b2.ToTable("Troops");

                                    b2.WithOwner()
                                        .HasForeignKey("StatsListTroopId");
                                });

                            b1.OwnsOne("ClashRoyaleApi.StatsList.HitpointsType", "Hitpoints", b2 =>
                                {
                                    b2.Property<int>("StatsListTroopId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("CloneHitpoints")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("CloneShieldHitpoints")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("DecoyHitpoints")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("Hitpoints")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("MaxHitpoints")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("ShieldHitpoints")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("TurretHitpoints")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("StatsListTroopId");

                                    b2.ToTable("Troops");

                                    b2.WithOwner()
                                        .HasForeignKey("StatsListTroopId");
                                });

                            b1.OwnsOne("ClashRoyaleApi.StatsList.RangeType", "Range", b2 =>
                                {
                                    b2.Property<int>("StatsListTroopId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<double?>("Long")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Medium")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Ranged")
                                        .HasColumnType("REAL");

                                    b2.Property<double?>("Short")
                                        .HasColumnType("REAL");

                                    b2.HasKey("StatsListTroopId");

                                    b2.ToTable("Troops");

                                    b2.WithOwner()
                                        .HasForeignKey("StatsListTroopId");
                                });

                            b1.Navigation("Count");

                            b1.Navigation("Damage");

                            b1.Navigation("Duration");

                            b1.Navigation("Hitpoints");

                            b1.Navigation("Range");
                        });

                    b.Navigation("Stats")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
