using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ClashRoyaleApi.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Troops",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    ElixirCost = table.Column<int>(type: "INTEGER", nullable: false),
                    Name = table.Column<string>(type: "TEXT", nullable: false),
                    Stats_Rarity_Common = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Rarity_Rare = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Rarity_Epic = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Rarity_Legendary = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Rarity_Champion = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Rarity_Evolution = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Rarity_Hero = table.Column<double>(type: "REAL", nullable: true),
                    Stats_TroopType_Troop = table.Column<double>(type: "REAL", nullable: true),
                    Stats_TroopType_Spell = table.Column<double>(type: "REAL", nullable: true),
                    Stats_TroopType_Building = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_Damage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_DamagePerSecond = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_CrownTowerDamage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_AreaDamage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_ChargeDamage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_DeathDamage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_RangedDamage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_TornadoDamage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_LandingDamage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_BonusDamage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_CrownTowerDamagePerPercent = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_MeleeDamage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_BarrageDamage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_WarpDamage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_PoisonDamagePerSecond = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_CrownTowerDamagePerSecond = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_PowerShotDamage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_BounceDamage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_SpawnDamage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_DashDamage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_PulseDamage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_ExtraChainDamage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_ReflectDamage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_ReflectedTowerDamage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_IceBlastDamage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_DamagePerBlast = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_CloseQuartersDamage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_RecoilDamage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_SniperDamage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_TurretDamage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_ComboDamage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_JumpDamage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_BuildingDamagePerSecond = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_PushbackDamage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Damage_TripleShotDamage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Hitpoints_Hitpoints = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Hitpoints_MaxHitpoints = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Hitpoints_TurretHitpoints = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Hitpoints_ShieldHitpoints = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Hitpoints_CloneHitpoints = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Hitpoints_CloneShieldHitpoints = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Hitpoints_DecoyHitpoints = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Count_Count = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Count_SpawnCount = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Count_BrigadeCount = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Count_SkeletonCount = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Count_BarrelCount = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Count_GoblinCount = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Count_SpearGoblinCount = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Count_RascalBoyCount = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Count_RascalGirlCount = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Count_BushGoblinCount = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Count_GoblinBrawlerCount = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Count_SniperAmmo = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Count_DecoyGoblinCount = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Count_GeneralCount = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Count_RiderCount = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Count_MinSkeletonCount = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Count_MaxSkeletonCount = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Count_GrenadeCount = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Count_DeathSpawnCount = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Count_ProjectileCount = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Count_TargetCount = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Count_ChargeCount = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Count_MaxCount = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Duration_SpawnSpeed = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Duration_Lifetime = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Duration_HotSpawnSpeed = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Duration_StunDuration = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Duration_FreezeDuration = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Duration_BannerLifetime = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Duration_Cooldown = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Duration_SlowdownDuration = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Duration_TauntDuration = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Duration_PulseDuration = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Duration_DeployTime = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Duration_InvincibilityDuration = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Duration_BoostDuration = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Duration_Duration = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Duration_PoisonDuration = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Duration_CookingTime = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Duration_TornadoDuration = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Duration_ProductionSpeed = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Duration_NetDuration = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Duration_NetCooldown = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Duration_CastTime = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Duration_DecoyDuration = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Duration_ChargedDuration = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Duration_SnareDuration = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Duration_InvisibilityDuration = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Range_Short = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Range_Medium = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Range_Long = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Range_Ranged = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Target_Ground = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Target_Air = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Target_Both = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Target_Buildings = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Speed_Slow = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Speed_Medium = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Speed_Fast = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Speed_VeryFast = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Movement_Ground = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Movement_Air = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_BackwardTeleport = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_Invisible = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_Dash = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_Clone = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_Stun = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_TroopSummon = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_DamageBoost = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_DamageReduction = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_ReflectProjectiles = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_Knockback = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_SideSwitchTeleport = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_SoulsCollect = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_MultiplesDash = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_Charge = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_Jump = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_DualForm = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_SecondaryAttack = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_Snare = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_KeepMaxDamage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_Resurrect = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_Curse = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_SpellSummon = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_Grab = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_Slow = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_SwitchToBuilding = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_AlliesBuff = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_Freeze = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_Heal = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_Shield = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_AlliesSpeedBoost = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_EnemiesSpeedReduction = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_Invincibility = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_Mirror = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_Redeploy = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_ElixirCollect = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_PullToCenter = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_SwitchToGround = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_SwitchToAir = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_BuildingSummon = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_Taunt = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_Barrage = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Mechanic_MultipleTroops = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Trigger_OnDeploy = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Trigger_OnAttack = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Trigger_OnHit = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Trigger_OnDamageTaken = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Trigger_OnDeath = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Trigger_OnDurationEnd = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Trigger_OnChargeComplete = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Trigger_OnTargetReached = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Trigger_OnClick = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Trigger_Passive = table.Column<double>(type: "REAL", nullable: true),
                    Stats_Trigger_Activation = table.Column<double>(type: "REAL", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Troops", x => x.Id);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Troops");
        }
    }
}
